from pprint import pprint

ballys=[
    "Hearing Accessible King",
    "Queen",
    "Executive Suite",
    "Accessible Queen",
    "Hearing Accessible Queen",
    "King",
    "Smoking Executive Suite",
    "Smoking Queen",
    "Smoking King",
    "Smoking Accessible Queen",
    "Lakeview King",
    "Lakeview Queen",
    "Accessible King",
    "2 Queen Accessible Sierra Suite",
    "2 Queen Sierra Suite",
    "Wedding Office",
    "Chapel",
    "1 King Sierra Suite",
    "Lakeview 1 King Sierra Suite",
    "Accessible 1 King Lakeview Sierra Suite",
    "Tahoe Suite",
    "Smoking 1 King Sierra Suite",
    "Smoking Tahoe Suite",
    "Smoking Accessible King",
    "Smoking Lakeview Queen",
    "Smoking 2 Queen Sierra Suite",
]
    
secpty = [
    "Directed Sale Room (3 Queen Beds)",
    "Standard Room (2 Queen Bed)",
    "Hard Rock - Lake View Balcony Suite",
    "Lakeview Standard Room (2 Queen Beds)",
    "Standard Room (1 King Bed)",
    "Lakeview Standard Room (1 King Bed)",
    "Art Room - Deceit District (1 King Bed)",
    "Direct Sale Room (1 King Bed)",
    "Art Room - Deceit District (2 Queen Beds)",
    "Hard Rock - Mountain View Suite",
    "Clavae Suite (1 King Bed)",
    "Knew Management Suite (1 King Bed)",
    "Hard Rock - Standard King",
    "Babyface Suite (2 Queen Beds)",
    "Babyface Suite (1 King Bed)",
    "Art Room -  Lust District (1 King Bed)",
    "Hard Rock - Lakeview 2 Queen",
    "Hard Rock - Lakeview Balcony King",
    "Hard Rock - Lakeview King",
    "Hard Rock - Pool View Balcony Suite",
    "Hard Rock - Lakeview Balcony 2 Queen",
    "Hard Rock - Standard 2 Queen",
    "Hard Rock - Balcony 2 Queen",
    "Art Room - Entitlement District (2 Queen Beds)",
    "Art Room - Gluttony District (2 Queen Beds)",
    "Shramp Direct Sale - Standard Room (1 King Bed)",
    "Art Room - Gluttony District (Lakeview 2 Queen)",
    "Art Room - Lust District (2 Queen Beds)",
    "Art Room - Gluttony District (1 King Bed)",
    "Art Room - Entitlement District (1 King Bed)",
]   

type_mapping = [
    {"Sierra": [{"Queen": [{1: "Babyface Suite (1 Queen)"},
                           {2: "Babyface Suite (2 Queen)"},]},
                {"King": [{1: "Babyface Suite (1 King)"},
                          {2: "Babyface Suite (2 Queen)"},]}]
    },                    
    {"Tahoe": "Clavae Suite (1 King)",
    },         
    {"Executive": "Knew Management Suite (1 King)",
    },
    {"King":[{1:"Standard Room (1 King)"},
             {2:"Standard Room (2 King)"},
    ]},
    {"Queen":[{1:"Standard Room (1 Queen)"},
             {2:"Standard Room (2 Queen)"},
    ]},
]

sec_filt = [elem for elem in secpty if "Hard Rock" not in elem and "Art Room" not in elem]

mappinz = [
        {"Hearing Accessible King": "Standard Room (1 King Bed)"}, 
        {"Queen": "Standard Room (2 Queen Bed)"},
        {"Executive Suite": "Knew Management Suite (1 King Bed)"},
        {"Accessible Queen": "Standard Room (2 Queen Bed)"},
        {"Hearing Accessible Queen": "Standard Room (2 Queen Bed)"},
        {"King": "Standard Room (1 King Bed)"},
        {"Smoking Executive Suite": "Knew Management Suite (1 King Bed)"},
        {"Smoking Queen": "Standard Room (2 Queen Bed)"},
        {"Smoking King": "Standard Room (1 King Bed)"},
        {"Smoking Accessible Queen": "Standard Room (2 Queen Bed)"},
        {"Lakeview King": "Lakeview Standard Room (1 King Bed)"},
        {"Lakeview Queen": "Lakeview Standard Room (2 Queen Beds)"},
        {"Accessible King": "Standard Room (1 King Bed)"},
        {"2 Queen Accessible Sierra Suite": "Babyface Suite (2 Queen Beds)"},
        {"2 Queen Sierra Suite": "Babyface Suite (2 Queen Beds)"},
        {"Wedding Office": "IGNORE"},
        {"Chapel": "IGNORE"},
        {"1 King Sierra Suite": "Babyface Suite (1 King Bed)"},
        {"Lakeview 1 King Sierra Suite": "Babyface Suite (1 King Bed)"},
        {"Accessible 1 King Lakeview Sierra Suite": "Babyface Suite (1 King Bed)"},
        {"Tahoe Suite": "Clavae Suite (1 King Bed)"},
        {"Smoking 1 King Sierra Suite": "Babyface Suite (1 King Bed)"},
        {"Smoking Tahoe Suite": "Clavae Suite (1 King Bed)"},
        {"Smoking Accessible King": "Standard Room (1 King Bed)"},
        {"Smoking Lakeview Queen": "Lakeview Standard Room (2 Queen Beds)"},
        {"Smoking 2 Queen Sierra Suite": "Babyface Suite (2 Queen Beds)"},
    ]


