#!/usr/bin/env bash
# Invoke various out-of-band tasks for roombot

ROOMBAHT_DJANGO_SECRET_KEY="@SECRET_KEY@"
ROOMBAHT_EMAIL_HOST_USER="@EMAIL_HOST_USER@"
ROOMBAHT_EMAIL_HOST_PASSWORD="@EMAIL_HOST_PASSWORD@"
ROOMBAHT_DB_PASSWORD="@DB_PASSWORD@"
ROOMBAHT_DB_HOST="@DB_HOST@"
ROOMBAHT_SEND_MAIL="@SEND_MAIL@"
ROOMBAHT_TMP="@TEMP@"
ROOMBAHT_JWT_KEY="@JWT_KEY@"
ROOMBAHT_HOST="@HOST@"
ROOMBAHT_LOGLEVEL="@LOGLEVEL@"
ROOMBAHT_SEND_ONBOARDING="@SEND_ONBOARDING@"
ROOMBAHT_IGNORE_TRANSACTIONS="@IGNORE_TRANSACTIONS@"
ROOMBAHT_ONBOARDING_BATCH="@ONBOARDING_BATCH@"

/opt/roombaht-backend/venv/bin/python3 /opt/roombaht-backend/manage.py send_onboarding
