# Generated by Django 4.1.1 on 2024-10-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
    ]
