# Generated by Django 4.1.1 on 2023-10-12 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('ticket', models.CharField(max_length=20, verbose_name='Ticket')),
                ('invitation', models.CharField(max_length=20, verbose_name='Invitation')),
                ('jwt', models.CharField(max_length=240, verbose_name='JWT')),
                ('room_number', models.CharField(max_length=20, verbose_name='RoomNumber')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Number')),
                ('name_take3', models.CharField(max_length=50, verbose_name='Take3Name')),
                ('name_hotel', models.CharField(max_length=50, verbose_name='HotelName')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
                ('swap_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='SwapCode')),
                ('swap_time', models.DateTimeField(blank=True, null=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.guest')),
            ],
        ),
    ]
