# Generated by Django 4.1.1 on 2023-11-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='check_in',
            field=models.DateField(blank=True, db_column='check_in', null=True),
        ),
        migrations.RenameField(
            model_name='room',
            old_name='check_in',
            new_name='_check_in',
        ),
        migrations.AlterField(
            model_name='room',
            name='check_out',
            field=models.DateField(blank=True, db_column='check_out', null=True),
        ),
        migrations.RenameField(
            model_name='room',
            old_name='check_out',
            new_name='_check_out',
        ),
    ]
