# Generated by Django 4.1.1 on 2023-11-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_room_check_in_out_setters'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='can_login',
            field=models.BooleanField(default=False, verbose_name='CanLogin'),
        ),
        migrations.AddField(
            model_name='guest',
            name='hotel',
            field=models.CharField("Hotel", max_length=20, null=True, blank=True)
        ),
        migrations.AddField(
            model_name='room',
            name='is_mountainview',
            field=models.BooleanField(default=False, verbose_name='MountainviewRoom'),
        ),
    ]
