# Generated by Django 4.1.1 on 2024-10-18 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_hardrock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='guest_notes',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_art',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_comp',
        ),
        migrations.RemoveField(
            model_name='room',
            name='notes',
        ),
    ]
