# Generated by Django 4.1.1 on 2024-10-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_hardrock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='is_art',
            field=models.BooleanField(default=False, verbose_name='ART'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_comp',
            field=models.BooleanField(default=False, verbose_name='Comped'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_hearing_accessible',
            field=models.BooleanField(default=False, verbose_name='Hearing Accessible'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_lakeview',
            field=models.BooleanField(default=False, verbose_name='Lakeview'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_mountainview',
            field=models.BooleanField(default=False, verbose_name='Mountainview'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_placed',
            field=models.BooleanField(default=False, verbose_name='Placed'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_smoking',
            field=models.BooleanField(default=False, verbose_name='Smoking'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='Special'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_swappable',
            field=models.BooleanField(default=False, verbose_name='Swappable'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name_hotel',
            field=models.CharField(max_length=50, verbose_name='Hotel'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name_take3',
            field=models.CharField(max_length=50, verbose_name='Room Type'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=20, verbose_name='Room Number'),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
