# Generated by Django 4.1.1 on 2024-10-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_remove_room_guest_notes_remove_room_is_art_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='swap_code_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
