# Generated by Django 4.1.1 on 2024-10-18 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_room_is_art_alter_room_is_comp_and_more'),
        ('reservations', '0004_remove_room_guest_notes_remove_room_is_art_and_more'),
    ]

    operations = [
    ]
