# Generated by Django 4.1.1 on 2024-10-28 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_room_primary_alter_room_secondary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_one', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reservations.guest')),
                ('guest_two', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reservations.guest')),
                ('room_one', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reservations.room')),
                ('room_two', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reservations.room')),
            ],
        ),
    ]
