# Generated by Django 4.1.1 on 2025-09-11 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_merge_20241018_0553'),
        ('reservations', '0007_swap'),
    ]

    operations = [
    ]
