#!/usr/bin/env bash
FOLDER="17GU6iDJiSMVZGtHL0jWVoBgyPuiqsUVs"

set -e

SCRIPTDIR=$( cd "${0%/*}" && pwd)
ROOTDIR="${SCRIPTDIR%/*}"

PUBLIC_DIR=""
PRIVATE_DIR="With Smoking Icons"

LAYOUTS_DIR="${ROOTDIR}/frontend/public/layouts"
TMPDIR="$(mktemp -d)"

cleanup() {
    if [ -d "$TMPDIR" ] ; then
	rm -rf "$TMPDIR"
    fi
}

problems() {
    2>&1 echo "Error: $*"
    exit 1
}

trap cleanup EXIT

if [ $# == 1 ] ; then
    if [ -d "$1" ] ; then
	echo "Using images from ${1}"
	cp -vr "${1}/"* "$TMPDIR"
    else
	problems "${1} is not a directory"
    fi
    shift
else
    "${ROOTDIR}/backend/.venv/bin/gdown" -O "$TMPDIR" --folder "$FOLDER"
    if [ "$(ls -l "$TMPDIR" | wc -l)" == 0 ] ; then
	problems "Nothing downloaded??"
    fi
fi

if [ -d "$LAYOUTS_DIR" ] ; then
    rm -rf "$LAYOUTS_DIR"
fi
if [ ! -d "$LAYOUTS_DIR" ] ; then
    mkdir -p "$LAYOUTS_DIR"
fi

# handle public images
for image in "${TMPDIR}/${PUBLIC_DIR}/"*.png ; do
    SRCFILE="$(basename "$image")"
    DESTFILE="$(sed -e 's/ //g' -e 's/-/_/' -e 's/\./th\./' <<< "$SRCFILE")"
    if grep -q '3th' <<< "$DESTFILE" ; then
	DESTFILE="${DESTFILE/th/rd}"
    fi
    THUMBFILE="${DESTFILE%.*}_thumb.png"
    cp "${TMPDIR}/${PUBLIC_DIR}/${SRCFILE}" "${LAYOUTS_DIR}/${DESTFILE}"
    echo "Fetched ${SRCFILE} as ${DESTFILE}"
    convert "${TMPDIR}/${PUBLIC_DIR}/${SRCFILE}" -format png -thumbnail 35x30 "${LAYOUTS_DIR}/${THUMBFILE}"
    echo "Generated thumbnail ${THUMBFILE}"
done

# for private images. different filename.
for image in "${TMPDIR}/${PRIVATE_DIR}/"*.png ; do
    SRCFILE="$(basename "$image")"
    DESTFILE="private_$(sed -e 's/ //g' -e 's/-/_/' -e 's/\./th\./' <<< "$SRCFILE")"
    if grep -q '3th' <<< "$DESTFILE" ; then
	DESTFILE="${DESTFILE/th/rd}"
    fi
    THUMBFILE="${DESTFILE%.*}_thumb.png"
    cp "${TMPDIR}/${PRIVATE_DIR}/${SRCFILE}" "${LAYOUTS_DIR}/${DESTFILE}"
    echo "Fetched ${PRIVATE_DIR}/${SRCFILE} as ${DESTFILE}"
    convert "${TMPDIR}/${PRIVATE_DIR}/${SRCFILE}" -format png -thumbnail 35x30 "${LAYOUTS_DIR}/${THUMBFILE}"
    echo "Generated thumbnail ${THUMBFILE}"
done
