#!/usr/bin/env bash

set -e

SCRIPTDIR=$( cd "${0%/*}" && pwd)
ROOTDIR="${SCRIPTDIR%/*}"
if [ -n "$ROOMBAHT_CONFIG" ] ; then
    echo "Using alternative config ${ROOMBAHT_CONFIG}"
    if [ ! -e "$ROOMBAHT_CONFIG" ] ; then
	echo "Unable to open alternate config, lollll"
	exit 2
    fi
else
    ROOMBAHT_CONFIG="dev.env"
fi
source "$ROOMBAHT_CONFIG"

uv run --python "${ROOTDIR}/backend/.venv" \
    "${ROOTDIR}/backend/manage.py" "$@"
