#!/usr/bin/env bash

set -e
SCRIPTDIR=$( cd "${0%/*}" && pwd)
ROOTDIR="${SCRIPTDIR%/*}"

SEC_FILE="${ROOTDIR}/.secret"
ENC_FILE="${ROOTDIR}/secrets.enc"
ENV_FILE="${ROOTDIR}/secrets.env"

problems() {
    2>&1 echo "Error $*"
    exit 1
}

encrypt() {
    openssl enc -aes-256-cbc -pbkdf2 \
	    -pass "file:${SEC_FILE}" \
	    -p -in "$ENV_FILE" \
	    -out "$ENC_FILE" > /dev/null || problems "unable to encrypt"
    rm "$ENV_FILE"
}

decrypt() {
    openssl enc -aes-256-cbc -d -pbkdf2 \
	    -pass "file:${SEC_FILE}" \
	    -p -in "$ENC_FILE" \
	    -out "$ENV_FILE" > /dev/null || problems "unable to decrypt"
}

[ $# -ge 1 ] || problems "invalid args"
ACTION="$1"
shift

[ -e "$SEC_FILE" ] || problems ".secret file is missing"

if [ "$ACTION" == "encrypt" ] ; then
    encrypt
elif [ "$ACTION" == "decrypt" ] ; then
    decrypt
elif [ "$ACTION" == "show" ] ; then
    decrypt
    if [ $# == 0 ] ; then
	cat "$ENV_FILE"
    elif [ $# == 1 ] ; then
	grep "$1" "$ENV_FILE" | cut -f 2 -d '=' | sed -e 's/"//g'
    else
	problems "invalid args"
    fi
    rm "$ENV_FILE"
else
    problems "invalid args"
fi
